language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: V1INSriQfd5sQ+30AOMUDjcVr6bmDW8Qdm7EaZDkFTx9GS7O/7/D76SyfPSBxWUQ8DgFHmoi3hv+euPw2fSRWg5kV/hnq7yuYQUfHqf+EKgwM9sNd03cMseb0rnpxqdUe8Q+VTNVxuJL/o0JUKaLizTdjcts06013RSNSsx3qqS1UTJsFvmknYuAHvVPPsK+eOqzNswc1Wp+k2GfXAVfW3wnqyJkw9GWMvAQJ1i6RWSXp2I6ZbrMLz9iw63qdRA04X1uOT6xJLGsRoK2aZyv6nUlXLKMrAidwcc7By3y79w/ZrE0dTOyQatd6DWKC78kT1mdVg7C7PQfqXl+dIO/niYnEYSRKnqe1zgT5jhasItM5Irb+LnG5/In5TrvVpVyCPb2aAERZghxoUFD/eReudY3t7ipGOomuKwPoNZJ9S25aIllGc+x4P7Q1bB21ss+Gk5I1jChPUBntfeSpITskCMAFmcSQvjDft0a/Pp9uYVj5EeFv3KkTYUNnV4EzXXnNDb+HgtfS6i+gXuj5adWFrM0uU/n0/ZdduroQzuuJ7tLafKyItawZzHAmAkNvV6iX2w7QuuJWI8DjuGqnaiEqQ6JO5YNlHxtr2neyFTEBpUUyAHwD9fNWxZkFJqc6a6T9T1S9nUTKaMN5U6wFBjrknYFA84xmj9x3ZM9NXlQC9A=
notifications:
  email:
    on_success: always
    on_failure: never
