language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: bhZgbEV8lk06CPo79LOwwyP5SWoZJqSG5WFkltKPtLgeYCCVQyheCnki/gPuj7E6Cyr9HFjNL/j3Jaa432WW9eVc2/qq2RrHU6p2aVastM0aLv3LShiWuO81o8e5vRTLX39E15+ZuU9aMG+fQoYtc4EEzukBCpGyOkCseMRxDtrGFl2soUTfROa6i6vh2ydPax53zpaS1lgaE7J/i8btnMEOPUsmlmFOVD1fmDWttjp2yO7deRgHNfrZ5fE2EWq6ZaatcwHbJJ7QJdc+mz4TVYpcpb6mRm7fcCcag5lO1TVGs/lopG/rZYEmP2b+OwgVqXYDK9/rhqHwL5DVnrZ5fHapC9WQvjzQ/sMQPUdOkEezr3aZv7/MpiNCRoV9RI9/Cf4u+KYLl/S1EfajUeRJFHklUzX+8tDDMQROEKj9utNnWv9SCMfQB8+2y537VsCZA5SzK5ed/9utle7hrKevk+sQq1i7Ye4oJgTy40ZzsMAwiGM7MEFddxiBDmMg07eLtsf1Jn0Ie2v3e9saBnik5cNrfSUY1e0X5AWmSKMYj+4HVlbA5f14iE7rUeUx4oGEaAuuaXmPEFS6fUvYUXR+lLTXb70qtXveFKsrvMKqoXCHtgtBJigQFXpLYvHF5pCP6b3+gA3/3f9pm/h0ADfi/q/6/YLCyLO/1CRA98G+8QU=
  app: softplan-ex-2
  on:
    repo: WesleyFreitas472/softplan-ex-2
notifications:
  email:
    on_success: always
    on_failure: never
