language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: Er9OltatLFh0KNzTVqHaBcBimoA9KWwwf01FBxYA+qpQFZcpBVldGjaVYiRiquItg8djZAEofSGda5bTne3oYSj4Ry3ULpalF+yuI4qCq5rbhS63reE00Tpo3Xjfw8B7IHZUpKKEXx8YVJGV7cbXa0UYNcZd0tvU8WO3hdY3hLBwcPVsPckWZ8bVVMtgyWbn2CUUVidNXMBjgB3mQoNKhiu4BjBvsDfzdZTxq6huwUR8ag8h7oRptayuqNBzwm4/TYTLkoYgnZSL705/qXW1WgrWjH6n24O5fPXFxN4Yzyg/+CreBUy0BDR+zvAS+Ei0xEqbN3OvLmNaQ5QKbpEYgXQj9OQRCdJK8JQO30KsUmXuHuELIoTVRgSNRAZie6zTDIURqzCOCq37aSNtFon5Hf1sZb1jr2WbS+0kL2c8haesC0jyM8gH7MCwd26zds2gDOZoet2IquyXGQUWKS4I2a9hMRtWYz4D7wMLbDGWiyXg7nfq54/ypPm3dwkqr+EXQfp0+8pnzM0PD23GBn07PiAkBRZtCSPy+DVrZ4S+tXk+IXo+qc2Tsa8LvO7G1891A/+9GP5lZxEDSq44VwZeKuCwIf0wvKsitLi7ONitKmbOLeYMjgw7emi4Swr0wjjQdOuRFJeebeeJjqAKHqk3Tzdk+5qkmpOoUSoW7pf7Mjg=
  app: values-softplan
notifications:
  email:
    on_success: always
    on_failure: never
