language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: OJE5RpjOS/hSDirmYLrIH8ecvkIqlmzULZbQnsIAs/qUbdQdbLI5RON66VXFY4NBD3ggzwQuMVXMIh31QLDSDA4BlDkmPrdMc3cNiaPg6Avn0RgdJvx5qXkAZenFvi0eH69AMu5qrVxopli9RwRNh/sGgoh24Kjwd092yPtktH/khLSs7bo7gDH1GUS0gxzUzAOTIBCImBVbpUtOkbf/kDcQ6lwHFdZhWIqlxDpYJB7i2yr/ge/Akr0HAPIhHCyjakipQK6HnVCin94y7pjv6FoeTALScsJaewWQPzffl65NVdfgJ+1VPvZ+Eo6W3JJWyOcBL4TwIPralobOPmXmEH1rAkOo4dj9TGA74RBG8cpqJP86X2TYAR213JbiZLEnSA1M7rc1KPFsLp4Uk7mOvkQcXhCJ0HSnLOd/uC6e/9EOpev1nvJBD9JbKKlLY9mTiCG5fiJYdcSkvVLbP2CZiOwpmmLkYZ9pxD8yOAZDSoduMhzSMoCjSglie/0zBI22qm/sQKpLrzAfnW0OKsZZWFArYO45YL+ePmU7KnsAJJTcA43StR8+D1jrKFhd+E+NqNgW+ANWjG1h5nLFkC54lNz6fl0H9NlpeoLQ08Zcagz5fP5dglDKOn5q39GI7m6j5iGOl9W9dwqScicn329gDfiSKp8eTmtzva63j3DV7Fk=
  app: values-softplan