language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: kw8GA1gcHwf8RqGwYvKnFNEykB7kfCdEMlcE9DWvZLnNmLJp2C8jGA9H7ooFAJJP7PIPdquoOmYK8ZKSXD49FQfFFbLPluaIgrLUrb27zzHDSIRelBsRqXErQFQTjuTkfNE5Pz8183xBJuTvXK2r4vy/NfD7y+NIZEOYk6LctxVeeyUxEQ5nZy0y+MxI9ug9fewC9aWZDlp5XuvaQtwRqw4qgcHhDLtYgp2PT6djOXn99Oe8LdF5YIC/HLVtedl5KoNUm0Pnw2oH0bx8ItDVZFWXF6JC/a98UOcIoa0gZYO+j2sKYSZgxYoAEgCwyTERcq1nfUkqM8spLxnnyf+rJPrKCS6Nwb2YToj5o4k+R4iSyQSq4LKq/DmPTcDuG/4lBIRTLa5yKgcD37SzrOjP4NCxo8N00uYk5L7VCGoXa9UQrpYTPrWprRhib8nf1wCf2uPixcDAqLG+E53ajPbgYzQ4qQeyC5zRAdPXU6oYgBjOHI+9VavCUlBrpVrllvt45Fx6/FYCLQF85Chmnnl67vaK8dIjPJP19CobGFZVBF04/D5JkuRWuXcp8AdJJ///gXEKeV7VR13lTTeKqx8IbnnDn+8DE14b0GnzdyPL5kF1J0U+nYX7L7DpKTczg0iQaN237O5Zy3Tz0UtncfpKYRrnft+Sn/KnDP+CDZcScis=
  app: values-softplan
notifications:
  email:
    on_success: always
    on_failure: never
