language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: VU8xpJqBu08WuawV8AurvNMNsyOAf1d0xfXVLTmZfQFhdJfAyzmDPMc/2YhgoY+Yt4ftadvmSj2/zjjVKCi7o1LmpyK/hsq9y4gH6yqF9qNYVzQz11i4+okgILucMvnniI5MtZkg2Q14BPFITUwM0YqCtbQDn7R0C/jPa92L5Vx3kyJxvm1AIlSanxFnmA5WZJnwtDS/v8wYtmBc9+KEXtu9019wydfEaySbyKVS9cBPl5E4IqJDV6wrsKvPuAs8ru6NoPT4mXn82ZDXUK5AzQhZo6XgDiKAqy2cbDAhQhxQuveDJO8s5rcbqcTFV96ujEbODVfd7P//qZ3ZoCIM8IXbSL7mjSqN6pf4+BGvwt/tszWNA1WXQjWxyU4TPRvkMm+/OMi/kYjwtVCT1vvzvR2MjMJp2MZE5Hh5rQ2Xu3t5te1nFkDiw4yEVQ39oYA1zZmN32wkUOm8lAurTvpwG4bHjQKrp5kzMpGg4HhUyLYm/czSQ3IFrx+v9NWLSIE1beAxSvmy2rSMwVvSIntrvwONh/OvP/i8SJcnHnJGI0eQ5fMdqWzF1wLfiy0+lfif9Jp8nCFUJyFU9Ohz0QicLM2FwRUYgVz60rmyTb2Kz3LeBWbKEkiDtjjXqZgvBHOp48v5LjCBCwaonCBuJT4mhHoMwOL/LO9OyE+RFe8HUA0=
  app: softplan-ex-2
  on:
    repo: WesleyFreitas472/softplan-ex-2
notifications:
  email:
    on_success: always
    on_failure: never
