language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: AKhzARAiCbPpqpdYRmD5pwIoTMmT3WOCgeUV7GMSyKnQJ4zRhohE2NqqL1S5n9sXzVvMub1WwxppJ2u5GRmdE19yrBR0+pUtV/c469KcMCeQipyPbpwuS1n5hg/91lIWK2k/p+f/O5a4oxuqwEf915a/aGnGimhf0hrnsU/tX0myrcDq9VB7w0bmgRhtcFTIxJoW0eCkdg84ZlxCIRdzN9o8q/Jmp3FlWwBL8Xoe4FsuHLEJfF2oNjqem5kPZv+JItYqjo+SP7GWIVO7e8iJWOQsMmpeA2v+Di0LEMuinFwtV6BfBeyNP8RPdTCivUjX3EkZOeYEloXJ5lmuqFh5wnllZl9RyxahRMpvhISKl9/UexOlQ9wVXk1pk4XRmX65CZTdjlqv/tq5vUdhcqVVdjhAdQSvL0Ov+lARPUJIdoHTEylYXIHFf0oK+/Mhy2oJnMD0geYxk7xCyR5M1qlrrMHXrE8vhONIQHd72jhDxkRkHy3ByAH4zpSyOQiRsjt0WecPRUOjC7e/+AV4dtESJvB4euoPdBnRrfQe3DqhhF0o/iY5/3Li2x993/cVWCDOBlCiKavFeesIQkYuwf4SAHzota6Oey6IN7v9Yf0fmBa5vcASmtpQNZ3ow3m+xF7U/RW8VtFHHYD/e/QF2bbhx5hRgVDfGqZ8pahkmyortTw=
  app: softplan-ex-2
  on:
    repo: WesleyFreitas472/softplan-ex-2
notifications:
  email:
    on_success: always
    on_failure: never
