language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: JCKHMI+EksbhUnfVLIt4Hhzeu43AzBZQHrIf/7VbiDEqs/yTKTwymEhfyIRnDO40WlXOZgE/reTPvQBRlLYe44k9f1P1JV78VU89utHsOOVnodh9e7FLuFSPMHHh9aBWDZjhWBPTaO0DRr9a6An6kO8+5buTB2sXGqNkGLrMGSyMafN1Nw5bSqPI2bJIpFL8DK7OpYmmpoAUj6udvEFityew9C+/ciP2znGA+M3acN3Bcv7L1pQCr71Gyf28v1bueWadrwQAzSn2VU3W3qM+S75Qo+81WcxGROonCvNmudHZ6Zli+caI5bSWghQ5MMLXY1AQLH8dJwM5mmR9iCfrcRLMcS9g8/y2bc4+X3ijioC57Awnxt6qskhKOjY9sc7MuCdXz+SR63Nz3KdjvuDxkbArxM0+3hpUcJlnSzcs87udpxxHzFhsUZ264P/u7J6bknZcfdikstmtAWp+kXmaIUZ3awKmc8J9MrAt75XQparRhRUZ7DQ/bmQwVdVovXSLs99bR0xC3Oj/v5htNKNF63e43lE/+TZKwthw3f3O0nc2C8waa5GfOFOoqNHKaYXX+cT8CFUu+aW3ZHjs9Ha5mdKVwMweW5LpCvvmpA3ao5G6E5OOVABT2/HCc+0tXWR8qV/scygQ6WAHzgAOQTUpgfsJ7WlHGHz6MHWs/Uvz/RA=
notifications:
  email:
    on_success: always
    on_failure: never
