language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: XvVlAIrxuvqzoHL0dPJ8ra+Fo3PBTf7grthonaep/C8snne/7yTyZmIh9D/ESrknhCut2FFvGpfwkI8Af5aQUbJsoVWsVTNArTlPlddGPdQRasXYDuCRsUbCZpht9kRByUAWIog+mIvIix5K5mcfWuSPctD9YEmJ8LY5uNWb25QYCMHc9NVV3Cl5+pZ6pnSr1ysFb3fAwmMYu8mX9ram1qyzJxu17p8VG9jDeVVoZRdZviEGdxEjzrmf1Eq+8YUmW1LsjPMwp1u0Mx2H26fSOjc44Gc3fP+40b4tFds+JmYEqE3dQZMEttHZR6IukMUxQ25OXWwOufUrjNgvBwEjFwtit0qxxIBLYqcd0g1uJ9L3O+GXdsCYkls+LRrd37lg7ZqnqiWPcu4+jsXI5U5E12KqngRMc2bEUlygBwz1NFOCdVlgNdsoue3k+f8baKvf1cRPoUDRx2YgUBI5YCHFdtcY4LKocddLgbbQkFQaYsXjZby7eeF5ihr64ZrnBjSDbzWEXAYrF4FFuhTXbVqXMg8y6RCDue7c+OwnbJwMbnu/2QXcJKLJXfftq/qEmJtT1yjYwM+jCGcks8olfPq2+aOwWJQYzvR5Y+UsPc9x46+3ZyAjJKw3utgsqLSscZdxMWE++/ISstrJG+fU6066975iBBGAQc/2jHeZs8VIg7E=
