language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: j7jLCS6f6PXrgYy5JSnJ1p411hNny9dhfurk/uarcdbz9NumpEoJtMAYJXcEM5WSm7sDMrUUaZmt4h69RHZE8vtoPd4W8XRTfgKAx38xi5rbbUAUxmwVaZvGItOxDAjje66aClFGZguOCVE4RYYtIABpJ2IpxhrjFy3eA6x+kKd/QWhO1jKxf/qjNeVIu+xvoq7Ol4q7c+lPUZFykdd1771yEODPkogEkjDQCvE3l21RvEYHDQD3gSD2e+TgFv/nxcU4tB2ZNbEEzKbp8vDP28KrKwFhqdst4zlGc+U1WVpsZrItt6JRZh40nWoh7ic1sBG8JE7HIOYfv7BfxtelhYo1kMS7HwKJRnqTa8meRR9+fytvVO+ysi4GI3eqqdhkHiZoYfV9iCUYODxSp2RPoMd4m883lMgepw6sjfEZa2FohUu0tFHXtsf0ohuapnBPEyZhF2JNIHZjzDW9OZptpnbUgymQNelX8dwjXNRHR5ykGLioW+nKMbo/hkL3f19c4EPayCzxj6B/O4sYKa6x5ml4EVp9GUois8jER5qdSpaOJk4eMOCtpik3NRTOAr7kpoXRRmz+zoNYBTxnaxe8dk2Ii+ex/aYuDH0kiuvEcIUfLTlopYqJtuJ5oYSEb2JDaGAnEbPiICdtHUZo3HeGLpvFwOLYRIVRnaNNGm7mW/0=
  app: values-softplan
  on:
    repo: wesleyfreitas472/softplan-ex-2
