language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: E+vM9ybpYEeQBFaqv8sn1EUpr5LLYzb7EVqxGYybDfnA1O4miMgAAvSYErzktFKuaoerydWR4/9gTzZ5vPz/Hp8Rt/iv4Jc1c1FHw4orLeidbtL0Ilzhgj/s50neqqxqYdNVJY7plQYqo+bnSy7qbS2fEUbi8MYoZkrlbPPXm8S+v91YzOA5hgjSWLtPJoY5aYvST6rWe57gg3Ijbe1sBwTsIegvA3xE1l3brYSNk7hcT9SGRVo7H7oEBR9FjB3AWvM7ujdeVgUSLLkd+UNHLoXyUk7RnajVqL/EGlbw/+K7EXuFN86psCZhMzbxN7IHbqmMy+/sMgDaz+hU6nmN12gnOYhEwDw4+rg2CagsB386VIvOxX4E3/KBntpvkDdp4oRC8Amhqau9B8B20yiyxUiyZ6kyNKQIv+2SRo86RdjhoPdMf5FuiFIMbnczFzZr2vsH/gZVQzxdalxdcyHYecey/gMYLCNMNlnLBykOm5WiV/KWKDNfpCFGiG/zqoAUn0NJpIvmYYH27viKTidaM4rdKTUaDP1qGXMU65Lg3EIQa91J2PVMoMUnWB0eFpNVQqJMeol48gZFVMJT56fkMYQdzMPZEeSFfsDm4InKSPVC3pMWiwGUuZUIvtmsOUnaV0OP1FYcqVl4O90iQIA9stCEM9vL2RHbEZIb7lPCamM=
notifications:
  email:
    on_success: always
    on_failure: never
