language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: EgGeHn8DbFspfkWJGGv1IktRDETjBT/PEjPSltADzgemlYqPXwIhR5KWeTWNf4R37WJLh1RnBzkRTlzHcc8d6Teq9Wtu8AENZwYxSiCmO/O1BD196gqgd/3wjG3GZ3vOYNeunZ4OuXF33jQAS+kfdvOd/beA4U8q8EP4VhNK/8lbJ0OAROieVhmvuqFrNPDXtcwgmLbn6kBQBUr3h/PCPyqH8A56M/HS95ElwlSrF5HF28fkYL2SqUawN93zDwviwev98FWPXxHR3hEOKxPGgcUBVr4tIwn1M+A44sVi/A56TDOtxFw2rpbiKPknNOYj7PkwT20R5wFocIepM4qnCZY8+VTJ2BT+fWM0CqGuVgL+2jiE+xlFdKnfAiqn49ET1UhS7OqY1KnkX8aqkHoU1ZizD2xBka6Lbl/yqpkeYiMxj7sbXSbYR4JND/6b3lv6E1qb0YeZeXWRB12TJFIzBrk8UUQjOiwriWCVL9HDOpowZCQvrl26slBSl8fgtA2mBv94sNgVeBwgIffmkR09DrAko0e2cQyMUQ7DIQ//U743zLCGBwRot4xiPzu0tXV9HewD1hTNx4nOjV7RbqBnGdYXNDHefQqmoPxpqNko9XHMUphWAOhisW8rCcUcrZYqAV6X7DbqH+rSl9RuPHSMgupfYizjJwOL+5jQ1ZTsVQU=
  app: softplan-ex-2
  on:
    repo: WesleyFreitas472/softplan-ex-2
notifications:
  email:
    on_success: always
    on_failure: never
