language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: mn87ondz15cuYl1w9BUj7jWmWlOjPlH9GmAafnlMmMiUhzaHd2IKMAOZeFKmNwjlUZdkFZDWmEllumDGqfn1QUdSvheawhwfeydMDVcp91sMc9jmn4eQYUmUv3Iv1Pu91JfxQ+iLCrD7sKglwPjbonWsBq5+58gQa7lnzIMY0EQ98AmPRt4iidWyM4rYpI+xWECZx7rhyCgFzeJZIrxP7UeedFa+Ym4jqILadzmoXwFSDFd4DUYcjkcY4sZ+fULGxSMi7yFMNBvEkXLazIwic74Ra8Nac7w9h9utz6SVzy6TIyg6Ecoa+pzGKUXMLV253a+gz4w7XXHoDUZk2Q/8eSXkX8FV2U2tiau/DPGmfM5rTipDsdaoxwXIieBdHyH0doxmSnN6r0xwDeGh3McRMf2xRujC2Il9pWBBGIe5YwbmJXQ0ykDi00fnP8TqmBSCGKrGdvixloJgFr0x/ZY1/EI+PvkAQQlWIBzMMYuSxIQqWTI+pRkaFIkmyE4rucvlKQ9iCZS18kOH3xdFIPhxW89zdUfEzcewApavcPnozW0Fax6ZAHD7fhsoOnie8deq8BilolH544jUoDfF6izul/sHwzoWLGzsHovQlTusy7wC5TNrFcaRqrfarK46P5y9tbxuX0A3DAVc1eOM89t7EfK1KKXQZEEDo+SdbSaVkTs=
  app: softplan-ex-2
  on:
    repo: WesleyFreitas472/softplan-ex-2
notifications:
  email:
    on_success: always
    on_failure: never
