language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: CXzXaQwG+7CiYNR6kLXOAIpJHdV67OmcHDCxthvSTGdsz3mR+0763WqYy2augfoafttHD7F3O6ZY6X3SeKzSRIW1xDZsXIcDP+72RTEbVzTRgyErnyDoi4daVL9/LCaf7ym4XJC+Pmy3Cb5sPG+Wkh124ew0S8yJvYEE6y64GdfFSCEfri1I9X5DGlrawKtk37lGklu7Vpwh+4lej8sujZu5PbfpXFCzB+5PYejytU0aYzQVwm5pGyLES5/hVqmeqlRvPzAplA5BRpab7MVjQiuXf29vydOYvo8MkcA2p6oeHofltMKhAK4Y1TVvTcLZwXMgUdSQfCrKt1L7WtqH4daorDruKlZu2VeUAdX0bcKEMDwJnHXuiAHs1AAY0tiZ5fphu58Jv8jDMiQVAPozj0XG7Xga3t6Y+Cb0OLl2tZ1WHYMV1SVzKQo7bt5hY5mUzHL2+0bAEBe1fAaxPbqV1Y3b2YI+sgaJRUGJEEAO3/CBVIlUzTW75qo5j36WUjX97ET5yJRvYI0Rh/lMuHL9/gWM3gc/RFoqzram86SDELK222WvKcZTzIYseh+SKFEzl01eJchQsNlptCCEDTlLFv7W11LjXQCgrGPSC2E71JDbl4nH3tmLk//9FP4FpfZFpEb/nod4FrmqLR27bMDiJ6P+2MZud+ch+iVCnVEpvoo=
