language: python
python: 3.6
install: pip install -r requirements.txt
script: python tests.py
deploy:
  provider: heroku
  api_key:
    secure: Cj5R6hBwL8PNqUKh2Ho0wIJFdRA7QOSGzVxp2W0UeVpO/a28DPhk56s1h6VcTiv8PzCaRkFtS14U4usc0HtrHcSOCNuP8eB1cK4ckvkYfIwaV1qE+40gQLW95EKdwnvD1dweuRIiMawcdDYD2MM9K+qraIWC6iq94tGzM6GbBkP7draoRUbBNZhxGCu9/5Uk4qSE1bK9ThWJCM4hTtl2YdYCP1+0Uysb8L+oEn64Q1rTGwBsr0Qnj/Xd4jkqDlqR/zbPdkkf/MuVx2q6BjMImWZs8XYLDNGQ/XXim7D5Wx4tSf5SGgX8l2mser1GNRZeySB5pczdHSAQL8Rpml1/lw7drjxWQU1RXD971cFz2emBrSIOL39urrDwti3QsZkF9Ve74GV+70CEvynjb3QM6dGvs49Fs9xoFYvcSsd+Haa90KCPZfr/0NYsesZtz30TTaiBDZLwji8NrMECOW7rrO+zh7erk6DE5keHIVuTPxvidzS2u0eyhaXt+P1C/No9efs0w98CtSpVd0+YQ31iC9606gKVKLMpj/j+cgFHeoRAA3Wk/BlPdVzJPGIJNrQk9Ajcs15pZRlhU5z+3DuC2bIw/iisdvYYuE+rZOwTwJ0aSThwi4M4CNOxQAY4uqW7j/C2UBQVKb9D/W5JBNHsEyos6aVV6URj9gh7OIAyGNo=
  app: values-softplan
